spring:
  application:
    name: SpringAppV5
  datasource:
    url: jdbc:postgresql://localhost:5432/V5_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true